name: Publish Python Package
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.8'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
        - name: Install project dependencies
          run: poetry install
 
        - name: Pytest
          run: poetry run pytest
        - name: Build package
          run: poetry build
        - name: Publish to PyPI
          env:
            POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
          run: poetry publish --username __token__ --password $POETRY_PYPI_TOKEN
